<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>34</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.kiwifruitdev.nonsensicalvideogenerator</ApplicationId>
    <ApplicationVersion>82</ApplicationVersion>
    <ApplicationDisplayVersion>8.2</ApplicationDisplayVersion>
    <DefineConstants>ANDROID</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.*" />
    <PackageReference Include="MonoGame.Extended" Version="4.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>